[tool.poetry]
name = "project_name"
version = "0.1.0"
description = "Описание проекта"
authors = ["Твое Имя "]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"